# Default style file for nitpick
# https://github.com/andreoliwa/nitpick/blob/v0.31.0/nitpick-style.toml

[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    # Suggest the current stable Python version for projects
    "py://nitpick/resources/python/39",


]

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "isort.skip", "isort.known_first_party"]
