# Default style file for nitpick
# https://github.com/andreoliwa/nitpick/blob/v0.31.0/nitpick-style.toml

[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    # Suggest the current stable Python version for projects
    "py://nitpick/resources/python/39",

    
    "py://nitpick/resources/python/absent",
    "py://nitpick/resources/python/bandit",
    "py://nitpick/resources/python/black",
    "py://nitpick/resources/python/flake8",
    "py://nitpick/resources/python/hooks",
    "py://nitpick/resources/python/isort",
    "py://nitpick/resources/python/mypy",
    "py://nitpick/resources/python/poetry",
    "py://nitpick/resources/python/pylint",
    "py://nitpick/resources/python/radon",
    "py://nitpick/resources/python/sonar-python",
    "py://nitpick/resources/python/tox",
    "py://nitpick/resources/python/autoflake",

    "py://nitpick/resources/any/commitizen",
    "py://nitpick/resources/any/editorconfig",    
    "py://nitpick/resources/any/hooks",
    "py://nitpick/resources/any/markdownlint",

]

[nitpick.files.absent]
".codeclimate.yml" = ""

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "isort.skip", "isort.known_first_party"]
